# Site settings
title: Ruby Mae Segal
email: rubymaesegal@gmail.com
url: https://bruxelles96.github.io/
description: "Adventures and Musings from Ruby Mae Segal"
skills: "Traveler - Digital Nomad - Actress"
meta_author: Segal Ruby

# Description
about1: "As a creative I search to grow through hands-on experience. My dream is to design, create and curate fun and exciting consumer print products such as home products, apparel, paper goods, and textiles. I have a thirst for real life experience and to experience humanity vastly, to expand my artistic view. I spent 10+ years studying theatre; performing in plays and musicals, learning patience and discipline in years of voice lessons, and studying to understand people in order to emulate them on stage. I gained confidence in front of a crowd, people skills, understanding for presentational design and spectacle."
about2: "I love design. Every time I walk into a store I become wide-eyed, studying every bauble and trinket. Culture is everything material and immaterial we surround ourselves with and value and I am so in awe with the beauty in which we can create and weave into our (and customers) lives. I believe that the things we buy and chose to surround ourselves with should be as bright, expressive and unique as every human being is. There are so many different canvases for outward expression out there, so why on earth should anything be ugly?"

# Color Settings (hex-codes without the leading hash-tag)
# I recommend using a site like this: https://www.canva.com/color-palette/
# It will help choose a starting pallete. But you'll need to do some tweaking.

#primary
#Background behind profile pic, and about section
#Choose this color somewhat conservatively. I recommend a darker color. Default: 1F2F42

#secondary
#Header, Footer, and large text labels
#This is your accent color, this can pop a little bit. Default: 1F67B4

#secondary-dark
#Section marker and copyright tag
#This color should be conservative, but compliment the accent color. Default: 233140

#background
#Background behind portfolio and contact forms. Default: 111111

color:
  primary: 1F2F42
  secondary: 1F67B4
  secondary-dark: 233140
  background: 111111
  text: ffffff

# Footer settings
footer:
  copyright: Ruby Segal
  location: Minneapolis, Minnesota
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://www.facebook.com/ruby.segal.3
  - title: linkedin
    url: http://www.linkedin.com/in/linkedinusername
  - title: instagram
    url: http://www.instagram.com/restlessrubymae/

# Relative Path Links
profile_picture: img/profile.png
#baseurl: /instafolio

credits: "Instafolio is developed by Nick Nothom, and utilizes Github Pages, Jekyll, and the Freelancer theme."

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Build settings
markdown: kramdown
permalink: pretty
