# Site settings
title: Nick Nothom
email: nicknothom@gmail.com
#url: https://nicknothom.github.io/
description: "Work and Life of Nick Nothom"
skills: "Designer - Engineer - Maker"
meta_author: Nothom Nick

#baseurl: /instafolio

about: "My current research is at the intersection of emotion and applied science. I am interested in devices that excite people and in building technologies that make lives better through sensors and algorithms. I am studying computer science and software development. I make stuff."

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1F2F42 #80B3FF
  #primary-rgb: "24,288,156" #"128,179,255"
  secondary: 1F67B4 #2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  background: 111111

# Footer settings
footer:
  copyright: Nicholas Nothom
  location: Saint Paul, Minnesota
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://www.facebook.com/nick.nothom
  - title: github
    url: http://github.com/nicknothom
  - title: linkedin
    url: http://www.linkedin.com/in/nicholasnothom/

# Build settings
markdown: kramdown
permalink: pretty
